apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: apache
  template:
    metadata:
      labels:
        component: apache
    spec:
      containers:
        - name: apache
          image: rickopsourced/apache
          ports:
            - containerPort: 8080
