    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: ingress-service-apache
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$1
    spec:
      rules:
        - host: hammertime.com 
          http:
            paths:
              - path: /?(.*)
                pathType: Prefix
                backend:
                  service:
                    name: apache-cluster-ip-service
                    port:
                      number: 8080
